### ISSUE TITLE
Exceptions on start in OSX

### ISSUE THREAD

**Issue by ainthek** [PatMartin/Dex#3]
when starting on OSX 

```
java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

I receive these errors:

```
Available Processors: 8
*** Searching for Dex Task inside your classpath...
Found Task: 'com.dexvis.dex.task.base.WebDriverTask'
--- Creating Property Sheet()
-- TASK: com.dexvis.dex.task.base.WebDriverTask@1f2830a3
  ** NEW CATEGORY: 'Web View'
PUT: 'Web View'
Found Task: 'com.dexvis.dex.task.base.WebTask'
java.lang.InstantiationException: com.dexvis.dex.task.base.WebTask
    at java.lang.Class.newInstance(Class.java:427)
    at com.dexvis.dex.Dex.getTasks(Dex.java:557)
    at com.dexvis.dex.Dex.init(Dex.java:222)
    at com.dexvis.dex.Dex.start(Dex.java:672)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
    at com.sun.javafx.application.LauncherImpl$$Lambda$70/505862938.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
    at com.sun.javafx.application.PlatformImpl$$Lambda$47/355629945.run(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
    at com.sun.javafx.application.PlatformImpl$$Lambda$49/453908573.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
    at com.sun.javafx.application.PlatformImpl$$Lambda$48/1915503092.run(Unknown Source)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.NoSuchMethodException: com.dexvis.dex.task.base.WebTask.<init>()
    at java.lang.Class.getConstructor0(Class.java:3082)
    at java.lang.Class.newInstance(Class.java:412)
    ... 13 more
```

and some more later....

any hints ? using latest version from git: SHA 02f24cd

**Comment by ainthek** [comment]
with http://dexvis.com/downloads/Dex-0.8.0.8.zip it prints no errors.

**Comment by PatMartin** [comment]
That exception in harmless, its dynamically searching the classpath for dex task and rejecting instantiation of an abstract class.
I thought that this had been fixed on github, though not in an official release.  I'll check when I get a chance to code.  But it's harmless.
The ThreadPool exhausted exception you sent before is a real problem.  I think you're running into some issues specific to OSX and JavaFX.  I don't have a working OSX box but you could perhaps run the application as a docker application.
- Pat

Date: Sun, 17 Jul 2016 01:56:26 -0700
