### ISSUE TITLE
Dex 0.8.0.8 - java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by ainthek** [PatMartin/Dex#4]
1. Add Read CSV task (pick data/presidents.csv)
2. Hit Execute (all seems ok)
3. When finished close the dialog with Cancel
4. Hit Execute again and you get errors:

OSX:

sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.5
## BuildVersion:   15F34

```
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

---

```
Available Processors: 8
*** Searching for Dex Task inside your classpath...
Found Task: 'com.dexvis.dex.task.base.WebDriverTask'
  ** NEW CATEGORY: 'Web View'
Found Task: 'com.dexvis.dex.task.base.WebTask'
Found Task: 'com.dexvis.dex.task.database.CreateJdbcTable'
  ** NEW CATEGORY: 'Database'
Found Task: 'com.dexvis.dex.task.database.QueryJdbc'
Found Task: 'com.dexvis.dex.task.info.CompareDatasources'
  ** NEW CATEGORY: 'Info'
Found Task: 'com.dexvis.dex.task.info.DescribeData'
Found Task: 'com.dexvis.dex.task.input.FileInput'
  ** NEW CATEGORY: 'Input'
Found Task: 'com.dexvis.dex.task.input.JarInspector'
Found Task: 'com.dexvis.dex.task.input.MultiFileInput'
Found Task: 'com.dexvis.dex.task.input.ReadCsv'
Found Task: 'com.dexvis.dex.task.input.TextInput'
Found Task: 'com.dexvis.dex.task.output.GroovyOutputTemplate'
  ** NEW CATEGORY: 'Output'
Found Task: 'com.dexvis.dex.task.output.WriteCsv'
Found Task: 'com.dexvis.dex.task.prg.GroovyScript'
  ** NEW CATEGORY: 'Programming'
Found Task: 'com.dexvis.dex.task.prg.JavaScript'
Found Task: 'com.dexvis.dex.task.prg.JythonScript'
Found Task: 'com.dexvis.dex.task.prg.P5Script'
Found Task: 'com.dexvis.dex.task.prg.RScript'
Found Task: 'com.dexvis.dex.task.prg.TMIScript'
Found Task: 'com.dexvis.dex.task.tablemanipulation.AddColumn'
  ** NEW CATEGORY: 'Table Manipulation'
Found Task: 'com.dexvis.dex.task.tablemanipulation.AddRowNumber'
Found Task: 'com.dexvis.dex.task.tablemanipulation.ColumnFilter'
Found Task: 'com.dexvis.dex.task.tablemanipulation.GroupColumns'
Found Task: 'com.dexvis.dex.task.tablemanipulation.ReplaceAll'
Found Task: 'com.dexvis.dex.task.tablemanipulation.SelectColumns'
Found Task: 'com.dexvis.dex.task.tablemanipulation.SplitColumns'
Found Task: 'com.dexvis.dex.task.tablemanipulation.TrimColumns'
Found Task: 'com.dexvis.dex.task.utilities.DataRecorder'
  ** NEW CATEGORY: 'Utilities'
Found Task: 'com.dexvis.dex.task.utilities.Documentation'
Found Task: 'com.dexvis.dex.task.utilities.Environment'
Found Task: 'com.dexvis.dex.task.utilities.ExecuteProcess'
Found Task: 'com.dexvis.dex.task.utilities.Google'
Found Task: 'com.dexvis.dex.task.utilities.GroovyFilter'
Found Task: 'com.dexvis.dex.task.utilities.Group'
Found Task: 'com.dexvis.dex.task.utilities.ViewData'
Found Task: 'com.dexvis.dex.task.vis.c3.AreaChart'
  ** NEW CATEGORY: 'Visualization:C3'
Found Task: 'com.dexvis.dex.task.vis.c3.BarChart'
Found Task: 'com.dexvis.dex.task.vis.c3.LineChart'
Found Task: 'com.dexvis.dex.task.vis.c3.LineChartMultiples'
Found Task: 'com.dexvis.dex.task.vis.c3.Scatterplot'
Found Task: 'com.dexvis.dex.task.vis.c3.StackedAreaChart'
Found Task: 'com.dexvis.dex.task.vis.c3.StackedBarChart'
Found Task: 'com.dexvis.dex.task.vis.c3.StepChart'
Found Task: 'com.dexvis.dex.task.vis.d3.CircularHeat'
  ** NEW CATEGORY: 'Visualization:D3'
Found Task: 'com.dexvis.dex.task.vis.d3.ClusteredForce'
Found Task: 'com.dexvis.dex.task.vis.d3.CoOccurrence'
Found Task: 'com.dexvis.dex.task.vis.d3.Force'
Found Task: 'com.dexvis.dex.task.vis.d3.IndentedTree'
Found Task: 'com.dexvis.dex.task.vis.d3.NodeLinkTree'
Found Task: 'com.dexvis.dex.task.vis.d3.PartitionLayout'
Found Task: 'com.dexvis.dex.task.vis.d3.Sankey'
Found Task: 'com.dexvis.dex.task.vis.d3.StackedRadar'
Found Task: 'com.dexvis.dex.task.vis.d3.SteamGraph'
Found Task: 'com.dexvis.dex.task.vis.d3.TensionMap'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.BarChart'
  ** NEW CATEGORY: 'Visualization:Dex Charts'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.C3Player'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.Chord'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.ChordMultiples'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.ClusteredForce'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.Dendrogram'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.DendrogramMultiples'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.DygraphLineChart'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.ForceDiagram'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.MotionBarChart'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.MotionChart'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.MotionCircleChart'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.MotionLineChart'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.Network'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.OrbitalLayout'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.ParCoor2Chord'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.ParCoor2Dendrogram'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.ParCoor2Table'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.ParallelCoordinates'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.RadarChart'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.RadialTree'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.Sankey'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.SankeyParticles'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.ScatterPlot'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.Sql2ParCoord'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.Sql2Table'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.SqlQuery'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.Sunburst'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.TitledTreemap'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.Treemap'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.dygraphs.LineChart'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.google.AreaChart'
  ** NEW CATEGORY: 'Visualization:Google'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.google.DiffBarChart'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.google.DiffPieChart'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.google.Timeline'
Found Task: 'com.dexvis.dex.task.vis.dexcharts.google.WordTree'
Found Task: 'com.dexvis.dex.task.vis.javafx.JavaFXBarChart'
  ** NEW CATEGORY: 'Visualization:JavaFX'
Found Task: 'com.dexvis.dex.task.vis.javafx.JavaFXBubbleChart'
Found Task: 'com.dexvis.dex.task.vis.javafx.JavaFXPieChart'
Found Task: 'com.dexvis.dex.task.vis.javafx.JavaFXXYChart'
Found Task: 'com.dexvis.dex.task.vis.nvd3.BarChart'
  ** NEW CATEGORY: 'Visualization:NVD3'
Found Task: 'com.dexvis.dex.task.vis.nvd3.BubbleChart'
Found Task: 'com.dexvis.dex.task.vis.nvd3.CrossFilter'
Found Task: 'com.dexvis.dex.task.vis.nvd3.DonutChart'
Found Task: 'com.dexvis.dex.task.vis.nvd3.LineChart'
Found Task: 'com.dexvis.dex.task.vis.nvd3.MultiBarChart'
Found Task: 'com.dexvis.dex.task.vis.nvd3.MultiHorBarChart'
Found Task: 'com.dexvis.dex.task.vis.nvd3.PieChart'
Found Task: 'com.dexvis.dex.task.vis.nvd3.StackedAreaChart'
Found Task: 'com.dexvis.dex.task.vis.prefuse.PrefuseGraphView'
  ** NEW CATEGORY: 'Visualization:Prefuse'
Found Task: 'com.dexvis.dex.task.vis.prefuse.PrefuseRadialGraphView'
Found Task: 'com.dexvis.dex.task.vis.prefuse.PrefuseStarburst'
Found Task: 'com.dexvis.dex.task.vis.prefuse.PrefuseTreeView'
Found Task: 'com.dexvis.dex.task.vis.table.BlueTable'
  ** NEW CATEGORY: 'Visualization:Table'
Found Task: 'com.dexvis.dex.task.vis.table.DataTable'
Found Task: 'com.dexvis.dex.task.vis.table.Grid'
Found Task: 'com.dexvis.dex.task.vis.table.SearchableTable'
Found Task: 'com.dexvis.dex.task.vis.uml.ClassDiagram'
  ** NEW CATEGORY: 'Visualization:UML'
Found Task: 'com.dexvis.dex.task.vis.uml.SequenceDiagram'
Found Task: 'com.dexvis.dex.task.vis.vis.AnimatedGraph3D'
  ** NEW CATEGORY: 'Visualization:Vis'
Found Task: 'com.dexvis.dex.task.vis.vis.BarChart'
Found Task: 'com.dexvis.dex.task.vis.vis.HierarchicalLayout'
Found Task: 'com.dexvis.dex.task.vis.vis.Network'
Found Task: 'com.dexvis.dex.task.vis.vis.Timeline'
Mouse Click Detected: 1
Mouse Click Detected: 1
Mouse Click Detected: 1
Mouse Click Detected: 2
Execute Workflow: 
Jul 17, 2016 11:16:13 AM com.sun.javafx.css.StyleConverterImpl getInstance
SEVERE: StyleConverterImpl : converter Class is null for : com.sun.javafx.scene.layout.region.CornerRadiiConverter
Jul 17, 2016 11:16:13 AM com.sun.javafx.css.StyleConverterImpl readBinary
SEVERE: could not deserialize com.sun.javafx.scene.layout.region.CornerRadiiConverter
could not deserialize com.sun.javafx.scene.layout.region.CornerRadiiConverter
Running: Read CSV
Execute Workflow: 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@46895d8 rejected from java.util.concurrent.ThreadPoolExecutor@1a89e426[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
    at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
    at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
    at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:678)
    at com.dexvis.dex.wf.SerialJob.execute(SerialJob.java:232)
    at com.dexvis.dex.wf.DexJobScheduler.execute(DexJobScheduler.java:14)
    at com.dexvis.dex.Dex.executeWorkflow(Dex.java:476)
    at com.dexvis.dex.Dex.lambda$15(Dex.java:262)
    at com.dexvis.dex.Dex$$Lambda$194/1000224704.handle(Unknown Source)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Node.fireEvent(Node.java:8390)
    at javafx.scene.control.Button.fire(Button.java:185)
    at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3758)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3486)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2495)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:350)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$350(GlassViewEventHandler.java:385)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$$Lambda$387/1752046680.get(Unknown Source)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:404)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:384)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:927)
```

**Comment by PatMartin** [comment]
From what I read on the internet, the error:
Jul 17, 2016 11:16:13 AM com.sun.javafx.css.StyleConverterImpl getInstance
SEVERE: StyleConverterImpl : converter Class is null for : com.sun.javafx.scene.layout.region.CornerRadiiConverter
Jul 17, 2016 11:16:13 AM com.sun.javafx.css.StyleConverterImpl readBinary
SEVERE: could not deserialize com.sun.javafx.scene.layout.region.CornerRadiiConverter
could not deserialize com.sun.javafx.scene.layout.region.CornerRadiiConvertercan be ignored.  Its some javafx problem and not specific to this.I will put some defensive logic in the serial thread pool when I get a chance.  Once I do that, I'll ping you back.  Looks like I really need to spend some time in OSX.- Pat
Date: Sun, 17 Jul 2016 02:20:35 -0700
